### ISSUE TITLE
Permissions necessary for BOLT to work?

### ISSUE THREAD

**Issue by nshilling** [DovetailSoftware/bolt#12]
Just went through BOLT install with a customer.  Observed the following:

Consistently receiving a 500.19 error, with mention in that of a permissions problem.

I ultimately had to add the local `IUSR` as well as the local `IIS_IUSRS` groups.  Once added with read/write/modify to the bolt directory - everything worked.

![image](https://cloud.githubusercontent.com/assets/431570/22609954/d5dfcb7e-ea28-11e6-98b2-95a12378438e.png)

This wasn't noted in the docs, but it seems every customer needs some sort of permission setup.  My local laptop does not need this for BOLT to work and I keep thinking we should better understand why these two groups are necessary sometimes and not others.

**Comment by gsherman** [comment]
added details to the readme regarding file system permissions.

Commit https://github.com/DovetailSoftware/bolt/commit/23323ccc4511f7971bddac1aeabe3e1baf6d7808
