### ISSUE TITLE
Consolidate the schema search from the many options into one search field

### ISSUE THREAD

**Issue by KevM** [DovetailSoftware/bolt#4]
Our current schema "search" UI

![image 202013-07-18 20at 2011 06 48 20am 1](https://f.cloud.github.com/assets/1565/820416/1229c548-efc4-11e2-9918-71060f197dee.png)

To make searching for things in the schema simpler we could have one search field which the user types a table, view, relation, field name and sees all the schema related results that match.

**Comment by gsherman** [comment]
wont do
